name: sc-dandelion-container
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13
  - setuptools
  - seaborn
  - scikit-learn
  - statsmodels
  - numba
  - polars
  - pyarrow
  - python-igraph
  - leidenalg
  - pip
  - pytest
  - tbb
  - rpy2
  - r-base
  - r-stringi
  - r-optparse
  - r-tigger
  - r-shazam
  - r-airr
  - r-alakazam
  - blast
  - pip:
      - scanpy>=1.7.0
      - biopython
      - receptor-utils
