name: dandelion
channels:
  - conda-forge
  - bioconda
dependencies:
  - numpy
  - setuptools
  - pandas
  - pandoc
  - pyyaml
  - seaborn
  - statsmodels
  - pytables>=3.8.0
  - pytest
  - blast
  - rpy2
  - bioconductor-edger
  - pip
  - tbb
  - pip:
      - numba
      - airr
      - changeo
      - matplotlib
      - nbsphinx
      - sphinx-autodoc-typehints
      - pytest-cov
      - .[scirpy,scrublet,palantir,dask,polars,tests] # This installs the current directory as a package
