name: Create Singularity Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to create"
        required: true

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code for the container build
        uses: actions/checkout@v4

      - name: Setup Singularity
        uses: singularityhub/install-singularity@main

      - name: Build Container
        run: |
          cd container
          sudo -E singularity build --notest sc-dandelion.sif sc-dandelion.def

      - name: Test Container
        id: test_container
        run: |
          cd container
          sudo singularity test --writable-tmpfs sc-dandelion.sif
          singularity run -B $PWD sc-dandelion.sif dandelion-preprocess --help
          if [ $? -ne 0 ]; then
            echo "Container test failed"
            exit 1
          fi

      - name: Sign and Verify Container
        if: success()
        run: |
          cd container
          echo ${{ secrets.SINGULARITY_KEY }} > private.key
          singularity sign --key private.key sc-dandelion.sif
          singularity verify sc-dandelion.sif

      - name: Login to Sylabs Library
        env:
          SINGULARITY_TOKEN: ${{ secrets.SINGULARITY_TOKEN }}
        run: |
          singularity remote login --password "$SINGULARITY_TOKEN"

      - name: Push to Sylabs Library
        if: success()
        run: |
          singularity push sc-dandelion.sif \
            library://kt16/default/sc-dandelion:${{ github.event.inputs.tag_name }}
