name: Create Singularity Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to create"
        required: true

jobs:
  container:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: container
    steps:
      - name: Check out code for the container build
        uses: actions/checkout@v4

      - name: Setup Singularity
        uses: singularityhub/install-singularity@main

      - name: Build Container
        run: |
          sudo -E singularity build --notest sc-dandelion.sif sc-dandelion.def

      - name: Test Container
        id: test_container
        run: |
          sudo singularity test --writable-tmpfs sc-dandelion.sif
          singularity run -B $PWD sc-dandelion.sif dandelion-preprocess --help
          if [ $? -ne 0 ]; then
            echo "Container test failed"
            exit 1
          fi

      - name: Sign and Verify Container
        if: success()
        env:
          SINGULARITY_KEY: ${{ secrets.SINGULARITY_KEY }}
        run: |
          printf '%s' "$SINGULARITY_KEY" | singularity key import /dev/stdin
          singularity sign --keyidx 0 sc-dandelion.sif
          singularity verify sc-dandelion.sif

      - name: Push to Sylabs Library
        if: success()
        env:
          SINGULARITY_TOKEN: ${{ secrets.SINGULARITY_TOKEN }}
        run: |
          echo "$SINGULARITY_TOKEN" > /tmp/sylabs_token
          singularity remote login --tokenfile /tmp/sylabs_token
          rm /tmp/sylabs_token
          singularity push sc-dandelion.sif library://kt16/default/sc-dandelion:${{ github.event.inputs.tag_name }}
