name: Create Singularity Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to create"
        required: true

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code for the container build
        uses: actions/checkout@v4

      - name: Setup Singularity
        uses: singularityhub/install-singularity@main

      - name: Build Container
        run: |
          cd container
          echo '${{ steps.extract_location.outputs.location }}' >> environment.yml
          sudo -E singularity build --notest sc-dandelion.sif sc-dandelion.def

      - name: Test Container
        id: test_container
        run: |
          cd container
          sudo singularity test --writable-tmpfs sc-dandelion.sif
          singularity run -B $PWD sc-dandelion.sif dandelion-preprocess --help
          if [ $? -ne 0 ]; then
            echo "Container test failed"
            exit 1
          fi

      - name: Create artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: sc-dandelion.sif
          path: container/sc-dandelion.sif # fixed: file is built inside container/
